matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"

    - os: windows
      language: node_js
      node_js: "10"

env:
  global:
    - GH_TOKEN=$GH_TOKEN
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - npm i

script:
  - echo GH_TOKEN
  - npm run release

branches:
  only:
    - master